namespace TesteTecnico.Application.Application.Common.Interfaces.Entities.EquipmentModelStateHourlyEarnings;

public record CreateEquipmentModelStateHourlyEarning(decimal Value, Guid EquipmentModelId, Guid EquipmentStateId);