spring:
  profiles:
    active: "prod"
  jpa:
    open-in-view: false

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    version: openapi_3_0
    path: /api-docs
  swagger-ui:
    use-root-path: true

api:
  description: API de Controle de Equipamentos - API desenvolvida para o Teste Tecnico para empresa Aiko.
  version: v6
  server:
    url: http://localhost:8080

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
  datasource:
    url: jdbc:h2:mem:teste_estagio_backend_v3;NON_KEYWORDS=VALUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        default_schema: operation
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgresDB:5432/test
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
